name: 'Authenticate Qbee Client'
description: 'Authenticate the qbee-cli client for subsequent operations'
branding:
  icon: log-in
  color: white
inputs:
  login:
    description: 'login name for qbee.io'
    required: true
  password:
    description: 'login password for qbee.io'
    required: true
  api_host:
    description: 'api host to use'
    required: false
    default: 'www.app.qbee.io'
runs:
  using: 'docker'
  image: 'Dockerfile'